package wjhj.orbital.sportsmatchfindingapp.maps;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public enum Country {
    AFGHANISTAN("Afghanistan", "AF"),
    ALBANIA("Albania", "AL"),
    ALGERIA("Algeria", "DZ"),
    AMERICAN_SAMOA("American Samoa", "AS"),
    ANDORRA("Andorra", "AD"),
    ANGOLA("Angola", "AO"),
    ANGUILLA("Anguilla", "AI"),
    ANTARCTICA("Antarctica", "AQ"),
    ANTIGUA_AND_BARBUDA("Antigua & Barbuda", "AG"),
    ARGENTINA("Argentina", "AR"),
    ARMENIA("Armenia", "AM"),
    ARUBA("Aruba", "AW"),
    AUSTRALIA("Australia", "AU"),
    AUSTRIA("Austria", "AT"),
    AZERBAIJAN("Azerbaijan", "AZ"),
    BAHAMAS("Bahamas", "BS"),
    BAHRAIN("Bahrain", "BH"),
    BANGLADESH("Bangladesh", "BD"),
    BARBADOS("Barbados", "BB"),
    BELARUS("Belarus", "BY"),
    BELGIUM("Belgium", "BE"),
    BELIZE("Belize", "BZ"),
    BENIN("Benin", "BJ"),
    BERMUDA("Bermuda", "BM"),
    BHUTAN("Bhutan", "BT"),
    BOLIVIA("Bolivia", "BO"),
    BOSNIA_AND_HERZEGOVINA("Bosnia & Herzegovina", "BA"),
    BOTSWANA("Botswana", "BW"),
    BOUVET_ISLAND("Bouvet Island", "BV"),
    BRAZIL("Brazil", "BR"),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", "IO"),
    BRITISH_VIRGIN_ISLANDS("British Virgin Islands", "VG"),
    BRUNEI("Brunei", "BN"),
    BULGARIA("Bulgaria", "BG"),
    BURKINA_FASO("Burkina Faso", "BF"),
    BURUNDI("Burundi", "BI"),
    CAMBODIA("Cambodia", "KH"),
    CAMEROON("Cameroon", "CM"),
    CANADA("Canada", "CA"),
    CAPE_VERDE("Cape Verde", "CV"),
    CARIBBEAN_NETHERLANDS("Caribbean Netherlands", "BQ"),
    CAYMAN_ISLANDS("Cayman Islands", "KY"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "CF"),
    CHAD("Chad", "TD"),
    CHILE("Chile", "CL"),
    CHINA("China", "CN"),
    CHRISTMAS_ISLAND("Christmas Island", "CX"),
    COCOS_KEELING_ISLANDS("Cocos (Keeling) Islands", "CC"),
    COLOMBIA("Colombia", "CO"),
    COMOROS("Comoros", "KM"),
    CONGO_BRAZZAVILLE("Congo - Brazzaville", "CG"),
    CONGO_KINSHASA("Congo - Kinshasa", "CD"),
    COOK_ISLANDS("Cook Islands", "CK"),
    COSTA_RICA("Costa Rica", "CR"),
    CROATIA("Croatia", "HR"),
    CUBA("Cuba", "CU"),
    CURACAO("Curaçao", "CW"),
    CYPRUS("Cyprus", "CY"),
    CZECHIA("Czechia", "CZ"),
    COTE_DIVOIRE("Côte d’Ivoire", "CI"),
    DENMARK("Denmark", "DK"),
    DJIBOUTI("Djibouti", "DJ"),
    DOMINICA("Dominica", "DM"),
    DOMINICAN_REPUBLIC("Dominican Republic", "DO"),
    ECUADOR("Ecuador", "EC"),
    EGYPT("Egypt", "EG"),
    EL_SALVADOR("El Salvador", "SV"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "GQ"),
    ERITREA("Eritrea", "ER"),
    ESTONIA("Estonia", "EE"),
    ETHIOPIA("Ethiopia", "ET"),
    FALKLAND_ISLANDS("Falkland Islands", "FK"),
    FAROE_ISLANDS("Faroe Islands", "FO"),
    FIJI("Fiji", "FJ"),
    FINLAND("Finland", "FI"),
    FRANCE("France", "FR"),
    FRENCH_GUIANA("French Guiana", "GF"),
    FRENCH_POLYNESIA("French Polynesia", "PF"),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories", "TF"),
    GABON("Gabon", "GA"),
    GAMBIA("Gambia", "GM"),
    GEORGIA("Georgia", "GE"),
    GERMANY("Germany", "DE"),
    GHANA("Ghana", "GH"),
    GIBRALTAR("Gibraltar", "GI"),
    GREECE("Greece", "GR"),
    GREENLAND("Greenland", "GL"),
    GRENADA("Grenada", "GD"),
    GUADELOUPE("Guadeloupe", "GP"),
    GUAM("Guam", "GU"),
    GUATEMALA("Guatemala", "GT"),
    GUERNSEY("Guernsey", "GG"),
    GUINEA("Guinea", "GN"),
    GUINEA_BISSAU("Guinea-Bissau", "GW"),
    GUYANA("Guyana", "GY"),
    HAITI("Haiti", "HT"),
    HEARD_AND_MCDONALD_ISLANDS("Heard & McDonald Islands", "HM"),
    HONDURAS("Honduras", "HN"),
    HONG_KONG_SAR_CHINA("Hong Kong SAR China", "HK"),
    HUNGARY("Hungary", "HU"),
    ICELAND("Iceland", "IS"),
    INDIA("India", "IN"),
    INDONESIA("Indonesia", "ID"),
    IRAN("Iran", "IR"),
    IRAQ("Iraq", "IQ"),
    IRELAND("Ireland", "IE"),
    ISLE_OF_MAN("Isle of Man", "IM"),
    ISRAEL("Israel", "IL"),
    ITALY("Italy", "IT"),
    JAMAICA("Jamaica", "JM"),
    JAPAN("Japan", "JP"),
    JERSEY("Jersey", "JE"),
    JORDAN("Jordan", "JO"),
    KAZAKHSTAN("Kazakhstan", "KZ"),
    KENYA("Kenya", "KE"),
    KIRIBATI("Kiribati", "KI"),
    KUWAIT("Kuwait", "KW"),
    KYRGYZSTAN("Kyrgyzstan", "KG"),
    LAOS("Laos", "LA"),
    LATVIA("Latvia", "LV"),
    LEBANON("Lebanon", "LB"),
    LESOTHO("Lesotho", "LS"),
    LIBERIA("Liberia", "LR"),
    LIBYA("Libya", "LY"),
    LIECHTENSTEIN("Liechtenstein", "LI"),
    LITHUANIA("Lithuania", "LT"),
    LUXEMBOURG("Luxembourg", "LU"),
    MACAU_SAR_CHINA("Macau SAR China", "MO"),
    MACEDONIA("Macedonia", "MK"),
    MADAGASCAR("Madagascar", "MG"),
    MALAWI("Malawi", "MW"),
    MALAYSIA("Malaysia", "MY"),
    MALDIVES("Maldives", "MV"),
    MALI("Mali", "ML"),
    MALTA("Malta", "MT"),
    MARSHALL_ISLANDS("Marshall Islands", "MH"),
    MARTINIQUE("Martinique", "MQ"),
    MAURITANIA("Mauritania", "MR"),
    MAURITIUS("Mauritius", "MU"),
    MAYOTTE("Mayotte", "YT"),
    MEXICO("Mexico", "MX"),
    MICRONESIA("Micronesia", "FM"),
    MOLDOVA("Moldova", "MD"),
    MONACO("Monaco", "MC"),
    MONGOLIA("Mongolia", "MN"),
    MONTENEGRO("Montenegro", "ME"),
    MONTSERRAT("Montserrat", "MS"),
    MOROCCO("Morocco", "MA"),
    MOZAMBIQUE("Mozambique", "MZ"),
    MYANMAR("Myanmar (Burma)", "MM"),
    NAMIBIA("Namibia", "NA"),
    NAURU("Nauru", "NR"),
    NEPAL("Nepal", "NP"),
    NETHERLANDS("Netherlands", "NL"),
    NEW_CALEDONIA("New Caledonia", "NC"),
    NEW_ZEALAND("New Zealand", "NZ"),
    NICARAGUA("Nicaragua", "NI"),
    NIGER("Niger", "NE"),
    NIGERIA("Nigeria", "NG"),
    NIUE("Niue", "NU"),
    NORFOLK_ISLAND("Norfolk Island", "NF"),
    NORTH_KOREA("North Korea", "KP"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", "MP"),
    NORWAY("Norway", "NO"),
    OMAN("Oman", "OM"),
    PAKISTAN("Pakistan", "PK"),
    PALAU("Palau", "PW"),
    PALESTINIAN_TERRITORIES("Palestinian Territories", "PS"),
    PANAMA("Panama", "PA"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG"),
    PARAGUAY("Paraguay", "PY"),
    PERU("Peru", "PE"),
    PHILIPPINES("Philippines", "PH"),
    PITCAIRN_ISLANDS("Pitcairn Islands", "PN"),
    POLAND("Poland", "PL"),
    PORTUGAL("Portugal", "PT"),
    PUERTO_RICO("Puerto Rico", "PR"),
    QATAR("Qatar", "QA"),
    ROMANIA("Romania", "RO"),
    RUSSIA("Russia", "RU"),
    RWANDA("Rwanda", "RW"),
    REUNION("Réunion", "RE"),
    SAMOA("Samoa", "WS"),
    SAN_MARINO("San Marino", "SM"),
    SAUDI_ARABIA("Saudi Arabia", "SA"),
    SENEGAL("Senegal", "SN"),
    SERBIA("Serbia", "RS"),
    SEYCHELLES("Seychelles", "SC"),
    SIERRA_LEONE("Sierra Leone", "SL"),
    SINGAPORE("Singapore", "SG"),
    SINT_MAARTEN("Sint Maarten", "SX"),
    SLOVAKIA("Slovakia", "SK"),
    SLOVENIA("Slovenia", "SI"),
    SOLOMON_ISLANDS("Solomon Islands", "SB"),
    SOMALIA("Somalia", "SO"),
    SOUTH_AFRICA("South Africa", "ZA"),
    SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS("South Georgia & South Sandwich Islands", "GS"),
    SOUTH_KOREA("South Korea", "KR"),
    SOUTH_SUDAN("South Sudan", "SS"),
    SPAIN("Spain", "ES"),
    SRI_LANKA("Sri Lanka", "LK"),
    ST_BARTHELEMY("St. Barthélemy", "BL"),
    ST_HELENA("St. Helena", "SH"),
    ST_KITTS_AND_NEVIS("St. Kitts & Nevis", "KN"),
    ST_LUCIA("St. Lucia", "LC"),
    ST_MARTIN("St. Martin", "MF"),
    ST_PIERRE_AND_MIQUELON("St. Pierre & Miquelon", "PM"),
    ST_VINCENT_AND_GRENADINES("St. Vincent & Grenadines", "VC"),
    SUDAN("Sudan", "SD"),
    SURINAME("Suriname", "SR"),
    SVALBARD_AND_JAN_MAYEN("Svalbard & Jan Mayen", "SJ"),
    SWAZILAND("Swaziland", "SZ"),
    SWEDEN("Sweden", "SE"),
    SWITZERLAND("Switzerland", "CH"),
    SYRIA("Syria", "SY"),
    SAO_TOME_AND_PRINCIPE("São Tomé & Príncipe", "ST"),
    TAIWAN("Taiwan", "TW"),
    TAJIKISTAN("Tajikistan", "TJ"),
    TANZANIA("Tanzania", "TZ"),
    THAILAND("Thailand", "TH"),
    TIMOR_LESTE("Timor-Leste", "TL"),
    TOGO("Togo", "TG"),
    TOKELAU("Tokelau", "TK"),
    TONGA("Tonga", "TO"),
    TRINIDAD_AND_TOBAGO("Trinidad & Tobago", "TT"),
    TUNISIA("Tunisia", "TN"),
    TURKEY("Turkey", "TR"),
    TURKMENISTAN("Turkmenistan", "TM"),
    TURKS_AND_CAICOS_ISLANDS("Turks & Caicos Islands", "TC"),
    TUVALU("Tuvalu", "TV"),
    US_OUTLYING_ISLANDS("U.S. Outlying Islands", "UM"),
    US_VIRGIN_ISLANDS("U.S. Virgin Islands", "VI"),
    UGANDA("Uganda", "UG"),
    UKRAINE("Ukraine", "UA"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE"),
    UNITED_KINGDOM("United Kingdom", "GB"),
    UNITED_STATES("United States", "US"),
    URUGUAY("Uruguay", "UY"),
    UZBEKISTAN("Uzbekistan", "UZ"),
    VANUATU("Vanuatu", "VU"),
    VATICAN_CITY("Vatican City", "VA"),
    VENEZUELA("Venezuela", "VE"),
    VIETNAM("Vietnam", "VN"),
    WALLIS_AND_FUTUNA("Wallis & Futuna","WF"),
    WESTERN_SAHARA("Western Sahara","EH"),
    YEMEN("Yemen","YE"),
    ZAMBIA("Zambia","ZM"),
    ZIMBABWE("Zimbabwe","ZW"),
    ALAND_ISLANDS("Åland Islands","AX");

    private String countryName;
    private String countryCode;
    private static Map<String, Country> namesMapping = new HashMap<>();
    static {
        for (Country country : values()) {
            namesMapping.put(country.getCountryName(), country);
        }
    }

    Country(String countryName, String countryCode) {
        this.countryName = countryName;
        this.countryCode = countryCode;
    }

    public static Country fromCountryName(String name) {
        if (namesMapping.containsKey(name)) {
            return namesMapping.get(name);
        }
        throw new IllegalArgumentException("Invalid country name: " + name);
    }

    public String getCountryCode() {
        return countryCode;
    }

    public String getCountryName() {
        return countryName;
    }

    public Locale getLocale() {
        return new Locale("", countryCode);
    }
}
